import type { AdminUser, Commune, DailyPoint, MaintenanceTicket, Reservation } from './api'

/**
 * Données fictives affichées quand l'API admin renvoie 401 ou 0 résultats.
 * Permet de voir le rendu des onglets Réservations / Maintenance avant
 * d'avoir branché un token admin valide ou des données réelles.
 *
 * Tous les UUID respectent le format pour passer la validation Zod côté pages.
 */

function isoMinutesAgo(min: number): string {
  return new Date(Date.now() - min * 60 * 1000).toISOString()
}

function isoMinutesFromNow(min: number): string {
  return new Date(Date.now() + min * 60 * 1000).toISOString()
}

function isoHoursAgo(h: number): string {
  return isoMinutesAgo(h * 60)
}

/** Série fictive pour le sparkline 7 jours. Profil "activité réaliste"
 *  (creux le mercredi, pic le week-end). Les dates sont calculées à chaque rendu. */
export function demoReservationsDaily(days = 7): DailyPoint[] {
  // Profil cyclique d0..d6 (dimanche → samedi)
  const profile = [22, 12, 14, 10, 18, 28, 31]
  const out: DailyPoint[] = []
  for (let i = days - 1; i >= 0; i--) {
    const d = new Date()
    d.setUTCHours(0, 0, 0, 0)
    d.setUTCDate(d.getUTCDate() - i)
    const dow = d.getUTCDay()
    const base = profile[dow] ?? 15
    // Légère variation déterministe basée sur le jour pour éviter le motif trop régulier
    const jitter = ((d.getUTCDate() * 7) % 5) - 2
    out.push({
      date: d.toISOString().slice(0, 10),
      count: Math.max(0, base + jitter),
    })
  }
  return out
}

export const DEMO_ADMIN_USERS: AdminUser[] = [
  {
    id: 'ffffffff-ffff-ffff-ffff-ffffffffff01',
    email: 'alice.martin@example.fr',
    displayName: 'Alice Martin',
    phone: '+33 6 11 22 33 44',
    role: 'citizen',
    trustScore: 100,
    totalReservations: 47,
    isBanned: false,
    bannedReason: null,
    commune: { id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee01', name: 'Paris 11e' },
    lastActiveAt: isoMinutesAgo(35),
    gdprDeleteRequestedAt: null,
    gdprDeletedAt: null,
    createdAt: isoHoursAgo(24 * 90),
  },
  {
    id: 'ffffffff-ffff-ffff-ffff-ffffffffff02',
    email: 'paul.durand@example.fr',
    displayName: 'Paul Durand',
    phone: '+33 6 55 66 77 88',
    role: 'citizen',
    trustScore: 95,
    totalReservations: 22,
    isBanned: false,
    bannedReason: null,
    commune: { id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee02', name: 'Lyon 7e' },
    lastActiveAt: isoHoursAgo(2),
    gdprDeleteRequestedAt: null,
    gdprDeletedAt: null,
    createdAt: isoHoursAgo(24 * 60),
  },
  {
    id: 'ffffffff-ffff-ffff-ffff-ffffffffff03',
    email: 'leila.benali@example.fr',
    displayName: 'Leïla Benali',
    phone: null,
    role: 'citizen',
    trustScore: 72,
    totalReservations: 14,
    isBanned: false,
    bannedReason: null,
    commune: { id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee01', name: 'Paris 11e' },
    lastActiveAt: isoHoursAgo(8),
    gdprDeleteRequestedAt: null,
    gdprDeletedAt: null,
    createdAt: isoHoursAgo(24 * 45),
  },
  {
    id: 'ffffffff-ffff-ffff-ffff-ffffffffff04',
    email: 'fraudster@spam.example',
    displayName: null,
    phone: null,
    role: 'citizen',
    trustScore: 12,
    totalReservations: 5,
    isBanned: true,
    bannedReason: '3 retours hors délai + 1 item endommagé non signalé',
    commune: null,
    lastActiveAt: isoHoursAgo(24 * 14),
    gdprDeleteRequestedAt: null,
    gdprDeletedAt: null,
    createdAt: isoHoursAgo(24 * 70),
  },
  {
    id: 'ffffffff-ffff-ffff-ffff-ffffffffff05',
    email: 'thomas.lefebvre@example.fr',
    displayName: 'Thomas Lefebvre',
    phone: '+33 6 12 34 56 78',
    role: 'citizen',
    trustScore: 88,
    totalReservations: 9,
    isBanned: false,
    bannedReason: null,
    commune: { id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee03', name: 'Marseille 8e' },
    lastActiveAt: isoHoursAgo(48),
    gdprDeleteRequestedAt: isoHoursAgo(24 * 3),
    gdprDeletedAt: null,
    createdAt: isoHoursAgo(24 * 120),
  },
  {
    id: 'ffffffff-ffff-ffff-ffff-ffffffffff06',
    email: 'sophie.r@example.fr',
    displayName: 'Sophie R.',
    phone: null,
    role: 'citizen',
    trustScore: 100,
    totalReservations: 1,
    isBanned: false,
    bannedReason: null,
    commune: { id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee01', name: 'Paris 11e' },
    lastActiveAt: isoHoursAgo(72),
    gdprDeleteRequestedAt: null,
    gdprDeletedAt: null,
    createdAt: isoHoursAgo(24 * 7),
  },
  {
    id: 'ffffffff-ffff-ffff-ffff-ffffffffff07',
    email: 'marc.tech@sportlocker.fr',
    displayName: 'Marc Tech',
    phone: '+33 6 98 76 54 32',
    role: 'operator',
    trustScore: 100,
    totalReservations: 0,
    isBanned: false,
    bannedReason: null,
    commune: null,
    lastActiveAt: isoHoursAgo(1),
    gdprDeleteRequestedAt: null,
    gdprDeletedAt: null,
    createdAt: isoHoursAgo(24 * 180),
  },
  {
    id: 'ffffffff-ffff-ffff-ffff-ffffffffff08',
    email: 'julie.r@sportlocker.fr',
    displayName: 'Julie R.',
    phone: null,
    role: 'operator',
    trustScore: 100,
    totalReservations: 0,
    isBanned: false,
    bannedReason: null,
    commune: null,
    lastActiveAt: isoHoursAgo(4),
    gdprDeleteRequestedAt: null,
    gdprDeletedAt: null,
    createdAt: isoHoursAgo(24 * 150),
  },
  {
    id: 'ffffffff-ffff-ffff-ffff-ffffffffff09',
    email: 'stanislas@sportlocker.fr',
    displayName: 'Stanislas C.',
    phone: null,
    role: 'admin',
    trustScore: 100,
    totalReservations: 0,
    isBanned: false,
    bannedReason: null,
    commune: null,
    lastActiveAt: isoMinutesAgo(2),
    gdprDeleteRequestedAt: null,
    gdprDeletedAt: null,
    createdAt: isoHoursAgo(24 * 365),
  },
]

export const DEMO_COMMUNES: Commune[] = [
  {
    id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee01',
    inseeCode: '75111',
    name: 'Paris 11e',
    postalCode: '75011',
    department: '75',
    region: 'Île-de-France',
    population: 147017,
    contractStart: '2025-09-01',
    contractEnd: '2027-08-31',
    monthlyFeeCents: 1500_00,
    contactEmail: 'contrats@mairie11.paris.fr',
    contactPhone: '+33 1 53 27 11 00',
    distributorCount: 8,
  },
  {
    id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee02',
    inseeCode: '69387',
    name: 'Lyon 7e',
    postalCode: '69007',
    department: '69',
    region: 'Auvergne-Rhône-Alpes',
    population: 84057,
    contractStart: '2026-01-01',
    contractEnd: '2027-12-31',
    monthlyFeeCents: 800_00,
    contactEmail: 'sports@mairie-lyon.fr',
    contactPhone: '+33 4 78 92 73 00',
    distributorCount: 4,
  },
  {
    id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee03',
    inseeCode: '13208',
    name: 'Marseille 8e',
    postalCode: '13008',
    department: '13',
    region: 'Provence-Alpes-Côte d\'Azur',
    population: 80022,
    contractStart: '2025-11-15',
    contractEnd: '2026-11-14',
    monthlyFeeCents: 1200_00,
    contactEmail: 'maires.adjoints@marseille.fr',
    contactPhone: '+33 4 91 55 88 00',
    distributorCount: 6,
  },
  {
    id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee04',
    inseeCode: '44109',
    name: 'Nantes',
    postalCode: '44000',
    department: '44',
    region: 'Pays de la Loire',
    population: 320732,
    contractStart: null,
    contractEnd: null,
    monthlyFeeCents: 0,
    contactEmail: 'pilote.sport@nantesmetropole.fr',
    contactPhone: null,
    distributorCount: 0,
  },
]

const DEMO_USERS = [
  { id: '11111111-1111-1111-1111-111111111111', email: 'alice.martin@example.fr',  displayName: 'Alice Martin' },
  { id: '22222222-2222-2222-2222-222222222222', email: 'paul.durand@example.fr',   displayName: 'Paul Durand' },
  { id: '33333333-3333-3333-3333-333333333333', email: 'leila.benali@example.fr',  displayName: 'Leïla Benali' },
  { id: '44444444-4444-4444-4444-444444444444', email: 'thomas.lefebvre@example.fr', displayName: 'Thomas Lefebvre' },
  { id: '55555555-5555-5555-5555-555555555555', email: 'sophie.r@example.fr',      displayName: null },
] as const

const DEMO_DISTRIBUTORS = [
  { id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1', name: 'Parc des Buttes-Chaumont', serialNumber: 'SL-PARIS-019' },
  { id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2', name: 'Berges de Seine — Île Saint-Louis', serialNumber: 'SL-PARIS-024' },
  { id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3', name: 'Place de la République', serialNumber: 'SL-PARIS-031' },
  { id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4', name: 'Parc Montsouris', serialNumber: 'SL-PARIS-007' },
] as const

const DEMO_ITEMS = [
  { id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1', typeName: 'Ballon de basket' },
  { id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2', typeName: 'Raquette de tennis' },
  { id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3', typeName: 'Frisbee' },
  { id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb4', typeName: 'Ballon de foot' },
  { id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb5', typeName: 'Boules de pétanque (set)' },
] as const

export const DEMO_RESERVATIONS: Reservation[] = [
  {
    id: 'cccccccc-cccc-cccc-cccc-cccccccccc01',
    status: 'active',
    createdAt: isoMinutesAgo(35),
    expiresAt: isoMinutesAgo(20),
    openedAt:  isoMinutesAgo(28),
    returnedAt: null,
    dueAt:     isoMinutesFromNow(180),
    extensionCount: 0,
    user: DEMO_USERS[0],
    distributor: DEMO_DISTRIBUTORS[0],
    item: DEMO_ITEMS[0],
  },
  {
    id: 'cccccccc-cccc-cccc-cccc-cccccccccc02',
    status: 'pending',
    createdAt: isoMinutesAgo(8),
    expiresAt: isoMinutesFromNow(7),
    openedAt:  null,
    returnedAt: null,
    dueAt:     null,
    extensionCount: 0,
    user: DEMO_USERS[1],
    distributor: DEMO_DISTRIBUTORS[1],
    item: DEMO_ITEMS[1],
  },
  {
    id: 'cccccccc-cccc-cccc-cccc-cccccccccc03',
    status: 'overdue',
    createdAt: isoHoursAgo(5),
    expiresAt: isoHoursAgo(4),
    openedAt:  isoHoursAgo(4),
    returnedAt: null,
    dueAt:     isoHoursAgo(1),
    extensionCount: 2,
    user: DEMO_USERS[2],
    distributor: DEMO_DISTRIBUTORS[2],
    item: DEMO_ITEMS[2],
  },
  {
    id: 'cccccccc-cccc-cccc-cccc-cccccccccc04',
    status: 'returned',
    createdAt: isoHoursAgo(3),
    expiresAt: isoHoursAgo(2),
    openedAt:  isoHoursAgo(2),
    returnedAt: isoMinutesAgo(45),
    dueAt:     isoMinutesFromNow(120),
    extensionCount: 1,
    user: DEMO_USERS[3],
    distributor: DEMO_DISTRIBUTORS[0],
    item: DEMO_ITEMS[3],
  },
  {
    id: 'cccccccc-cccc-cccc-cccc-cccccccccc05',
    status: 'cancelled',
    createdAt: isoHoursAgo(8),
    expiresAt: isoHoursAgo(7),
    openedAt:  null,
    returnedAt: null,
    dueAt:     null,
    extensionCount: 0,
    user: DEMO_USERS[4],
    distributor: DEMO_DISTRIBUTORS[3],
    item: DEMO_ITEMS[4],
  },
  {
    id: 'cccccccc-cccc-cccc-cccc-cccccccccc06',
    status: 'returned',
    createdAt: isoHoursAgo(26),
    expiresAt: isoHoursAgo(25),
    openedAt:  isoHoursAgo(25),
    returnedAt: isoHoursAgo(22),
    dueAt:     isoHoursAgo(21),
    extensionCount: 0,
    user: DEMO_USERS[0],
    distributor: DEMO_DISTRIBUTORS[1],
    item: DEMO_ITEMS[1],
  },
  {
    id: 'cccccccc-cccc-cccc-cccc-cccccccccc07',
    status: 'expired',
    createdAt: isoHoursAgo(48),
    expiresAt: isoHoursAgo(47),
    openedAt:  null,
    returnedAt: null,
    dueAt:     null,
    extensionCount: 0,
    user: DEMO_USERS[2],
    distributor: DEMO_DISTRIBUTORS[2],
    item: DEMO_ITEMS[2],
  },
  {
    id: 'cccccccc-cccc-cccc-cccc-cccccccccc08',
    status: 'active',
    createdAt: isoMinutesAgo(95),
    expiresAt: isoMinutesAgo(80),
    openedAt:  isoMinutesAgo(87),
    returnedAt: null,
    dueAt:     isoMinutesFromNow(60),
    extensionCount: 0,
    user: DEMO_USERS[3],
    distributor: DEMO_DISTRIBUTORS[3],
    item: DEMO_ITEMS[0],
  },
]

export const DEMO_MAINTENANCE_TICKETS: MaintenanceTicket[] = [
  {
    id: 'dddddddd-dddd-dddd-dddd-dddddddddd01',
    status: 'open',
    severity: 5,
    title: 'Casier #3 bloqué — verrou ne s\'ouvre plus',
    description: 'Trois retours utilisateur cette semaine. Probable rupture du solénoïde, intervention urgente requise.',
    resolutionNote: null,
    resolvedAt: null,
    createdAt: isoHoursAgo(2),
    updatedAt: isoHoursAgo(2),
    distributor: DEMO_DISTRIBUTORS[0],
    assignee: null,
  },
  {
    id: 'dddddddd-dddd-dddd-dddd-dddddddddd02',
    status: 'open',
    severity: 3,
    title: 'Lecteur QR encrassé',
    description: 'Taux d\'échec de scan élevé observé via la télémétrie firmware (38% sur 24h).',
    resolutionNote: null,
    resolvedAt: null,
    createdAt: isoHoursAgo(8),
    updatedAt: isoHoursAgo(8),
    distributor: DEMO_DISTRIBUTORS[2],
    assignee: null,
  },
  {
    id: 'dddddddd-dddd-dddd-dddd-dddddddddd03',
    status: 'open',
    severity: 2,
    title: 'Étiquette d\'identification décollée',
    description: 'Cosmétique. À recoller lors du prochain passage technicien.',
    resolutionNote: null,
    resolvedAt: null,
    createdAt: isoHoursAgo(30),
    updatedAt: isoHoursAgo(30),
    distributor: DEMO_DISTRIBUTORS[1],
    assignee: null,
  },
  {
    id: 'dddddddd-dddd-dddd-dddd-dddddddddd04',
    status: 'in_progress',
    severity: 4,
    title: 'Heartbeat manquant depuis 12h',
    description: 'Distributeur silencieux. Probable problème réseau ou alimentation. Tech sur place.',
    resolutionNote: null,
    resolvedAt: null,
    createdAt: isoHoursAgo(14),
    updatedAt: isoHoursAgo(1),
    distributor: DEMO_DISTRIBUTORS[3],
    assignee: { id: '66666666-6666-6666-6666-666666666666', email: 'tech1@sportlocker.fr', displayName: 'Marc Tech' },
  },
  {
    id: 'dddddddd-dddd-dddd-dddd-dddddddddd05',
    status: 'in_progress',
    severity: 3,
    title: 'Calibration RFID dérive',
    description: 'Faux-positifs détectés sur les items 4 et 7. Tag à reprogrammer.',
    resolutionNote: null,
    resolvedAt: null,
    createdAt: isoHoursAgo(20),
    updatedAt: isoHoursAgo(3),
    distributor: DEMO_DISTRIBUTORS[0],
    assignee: { id: '77777777-7777-7777-7777-777777777777', email: 'tech2@sportlocker.fr', displayName: 'Julie R.' },
  },
  {
    id: 'dddddddd-dddd-dddd-dddd-dddddddddd06',
    status: 'resolved',
    severity: 4,
    title: 'Panneau solaire encrassé — batterie à 22%',
    description: 'Détecté via heartbeat. Tension chute en fin de journée.',
    resolutionNote: 'Nettoyage panneau + ajustement angle. Charge nominale restaurée (96% le lendemain).',
    resolvedAt: isoHoursAgo(50),
    createdAt:  isoHoursAgo(72),
    updatedAt:  isoHoursAgo(50),
    distributor: DEMO_DISTRIBUTORS[2],
    assignee: { id: '66666666-6666-6666-6666-666666666666', email: 'tech1@sportlocker.fr', displayName: 'Marc Tech' },
  },
  {
    id: 'dddddddd-dddd-dddd-dddd-dddddddddd07',
    status: 'wontfix',
    severity: 1,
    title: 'Bruit léger ventilation Raspberry Pi',
    description: 'Signalé par riverain. Niveau sonore < 30dB à 1m. Pas d\'action prévue.',
    resolutionNote: 'Niveau acceptable. Ticket fermé sans intervention.',
    resolvedAt: isoHoursAgo(100),
    createdAt:  isoHoursAgo(120),
    updatedAt:  isoHoursAgo(100),
    distributor: DEMO_DISTRIBUTORS[1],
    assignee: null,
  },
]
